settings:
  title: 'Status Page'
  url: 'https://status.stendhal.ai'
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wallkanda-front
    name: The Wallkanda Website
    url: 'https://beta.wallkanda.art'
    method: GET
    expectStatus: 200
 
  - id: wallkanda-api
    name: The Wallkanda API
    url: 'https://api.beta.wallkanda.art/health'
    method: GET
    expectStatus: 200
  
  - id: stendhal-website
    name: Stendhal Website
    description: 'The Web3 toolbox for Street-artists.'
    url: 'https://stendhal.ai'
    method: GET
    expectStatus: 200
